package crawlerdetector

// CrawlersList is list of crawlers/spiders/bots
func CrawlersList() []string {
	return []string{
		" YLT",
		"(^| )sentry\\/",
		"007ac9 Crawler",
		"008s\\/",
		"192\\.comAgent",
		"2ip\\.ru",
		"360Spider",
		"404checker",
		"404enemy",
		"80legs",
		"A6-Indexer",
		"ADmantX",
		"AHC",
		"AHC\\/",
		"AISearchBot",
		"APIs-Google",
		"ASPSeek",
		"Abonti",
		"Aboundex",
		"Accoona-AI-Agent",
		"Acunetix",
		"AdAuth\\/",
		"AddThis",
		"Adidxbot",
		"AdsBot-Google([^-]|$)",
		"AdsBot-Google-Mobile",
		"AdsTxtCrawler",
		"AdvBot",
		"Advanced Email Extractor v",
		"Ahrefs(Bot|SiteAudit)",
		"Airmail",
		"Alibaba\\.Security\\.Heimdall",
		"AllSubmitter",
		"Alligator",
		"AlphaBot",
		"Amazon CloudFront",
		"Anarchie",
		"AndersPinkBot",
		"AndroidDownloadManager",
		"Anemone",
		"AngleSharp\\/",
		"Ant\\.com",
		"Anturis Agent",
		"AnyEvent-HTTP\\/",
		"Apache Droid",
		"Apache-HttpAsyncClient\\/",
		"Apache-HttpClient",
		"Apache-HttpClient\\/",
		"ApacheBench\\/",
		"Apercite",
		"Apexoo",
		"AportWorm\\/[0-9]",
		"AppBeat\\/[0-9]",
		"AppEngine-Google",
		"AppEngine-Google",
		"AppStoreScraperZ",
		"Applebot",
		"Arachmo",
		"Arachnophilia",
		"ArchiveBot",
		"Arukereso",
		"AskQuickly",
		"Asterias",
		"Astute",
		"Attach",
		"Autonomy",
		"B-l-i-t-z-B-O-T",
		"BBBike",
		"BCKLINKS",
		"BDCbot",
		"BDFetch",
		"BIGLOTRON",
		"BLEXBot\\/",
		"BLP_bbot",
		"BPImageWalker",
		"BTWebClient",
		"BUbiNG",
		"BackStreet",
		"BackWeb",
		"Backlink-Ceck",
		"Bad-Neighborhood",
		"Badass",
		"Baidu-YunGuanCe",
		"Baiduspider",
		"Bandit",
		"Barkrowler",
		"BatchFTP",
		"Battleztar\\ Bazinga",
		"BazQux",
		"BegunAdvertising\\/",
		"BehloolBot",
		"BigBozz",
		"Bigfoot",
		"BingLocalSearch",
		"BingPreview",
		"BingPreview\\/",
		"Bitacle",
		"BlackWidow",
		"Black\\ Hole",
		"Blackboard Safeassign",
		"BlogPulseLive",
		"BlogSearch",
		"Bloglovin",
		"Blogtrottr",
		"BlowFish",
		"Boardreader",
		"BomboraBot",
		"Bot.AraTurka.com",
		"BoxcarBot",
		"Braintree-Webhooks",
		"Branch Metrics API",
		"Branch-Passthrough",
		"BrandVerity",
		"Brandprotect",
		"Brandwatch",
		"Brodie\\/",
		"Browsershots",
		"Buck\\/",
		"Buddy",
		"BuiltWith",
		"Bullseye",
		"BunnySlippers",
		"Burf Search",
		"Butterfly\\/",
		"BuzzSumo",
		"CAAM\\/[0-9]",
		"CC Metadata Scaper",
		"CCBot",
		"CERT\\.at-Statistics-Survey",
		"CISPA Vulnerability Notification",
		"CJNetworkQuality",
		"CSHttp",
		"CakePHP",
		"Calculon",
		"CapsuleChecker",
		"CaretNail",
		"Cegbfeieh",
		"Cerberian Drtrs",
		"ChangesMeter\\/",
		"Charlotte",
		"CheckHost",
		"CherryPicker",
		"ChinaClaw",
		"Chirp\\/[0-9]",
		"Chlooe",
		"CirrusExplorer\\/",
		"Citoid",
		"Clarsentia",
		"Cliqzbot\\/",
		"CloudEndure",
		"CloudFlare-AlwaysOnline",
		"Cloud\\ mapping",
		"Cloudinary\\/[0-9]",
		"CommaFeed",
		"Commons-HttpClient",
		"Comodo SSL Checker",
		"Companybook-Crawler",
		"ContextAd Bot",
		"CookieReports\\.com",
		"CopyRightCheck",
		"Copyscape",
		"Cosmos4j\\.feedback",
		"Covario-IDS",
		"CrawlForMe\\/[0-9]",
		"Crescent",
		"Crowsnest",
		"CrunchBot",
		"CrystalSemanticsBot",
		"Curious George",
		"CyberPatrol",
		"DMBrowser",
		"DNS-Tools Header-Analyzer",
		"DNSPod-reporting",
		"DTS\\ Agent",
		"DareBoost",
		"DataCha0s",
		"DataXu",
		"DatabaseDriverMysqli",
		"Datafeedwatch",
		"DataparkSearch",
		"Daum(oa)?[ \\/][0-9]",
		"Daum\\/",
		"Demon",
		"DeuSu",
		"DeuSu\\/",
		"Devil",
		"Diffbot\\/",
		"Digg Deeper",
		"Digg",
		"Digincore bot",
		"Digincore",
		"DigitalPebble",
		"Dirbuster",
		"Discordbot",
		"Dispatch\\/",
		"Disqus",
		"DittoSpyder",
		"DnyzBot",
		"Dolphin http client\\/",
		"Domain Re-Animator Bot",
		"DomainAppender",
		"DomainStatsBot",
		"Donuts Content Explorer",
		"Download\\ Wonder",
		"DowntimeDetector",
		"Dragonfly File Reader",
		"Drip",
		"Drupal \\(\\+http:\\/\\/drupal\\.org\\/\\)",
		"DuckDuckBot",
		"DuckDuckGo-Favicons-Bot",
		"EARTHCOM",
		"ECCP",
		"EMail Exractor",
		"EMail\\ Wolf",
		"EZID",
		"Easy-Thumb",
		"EasyDL",
		"Ebingbong",
		"Ecxi",
		"EirGrabber",
		"ElectricMonk",
		"Email%20Extractor%20Lite",
		"EmailWolf",
		"Embed PHP Library",
		"Embedly",
		"EventMachine HttpClient",
		"Everwall Link Expander",
		"EveryoneSocialBot",
		"Evidon",
		"Evrinid",
		"ExactSearch",
		"ExaleadCloudview",
		"Excel\\/",
		"Exif Viewer",
		"ExperianCrawlUK",
		"Exploratodo",
		"Express WebPictures",
		"ExtLinksBot",
		"ExtractorPro",
		"Extreme\\ Picture\\ Finder",
		"EyeNetIE",
		"FAST Enterprise Crawler",
		"FAST-WebCrawler",
		"FHscan",
		"Facebot",
		"Faraday v",
		"FavOrg",
		"Faveeo",
		"Favicon downloader",
		"Feed Wrangler",
		"FeedBooster",
		"FeedBucket",
		"FeedBunch\\/[0-9]",
		"FeedBurner",
		"FeedChecker",
		"Feedbin",
		"Feedfetcher-Google",
		"Feedly",
		"Feedspot",
		"Feedspotbot\\/",
		"Feedwind\\/[0-9]",
		"FemtosearchBot",
		"Fetch API",
		"Fetch\\/",
		"Fetch\\/[0-9]",
		"Fever",
		"Fever\\/[0-9]",
		"Fimap",
		"Flamingo_SearchEngine",
		"FlashGet",
		"FlipboardBrowserProxy",
		"FlipboardProxy",
		"FlipboardRSS",
		"Flock\\/",
		"Flunky",
		"FoundSeoTool\\/[0-9]",
		"FreeWebMonitoring SiteChecker",
		"Freeuploader",
		"Funnelback",
		"Fyrebot",
		"G-i-g-a-b-o-t",
		"GAChecker",
		"GIS-LABS",
		"GT::WWW",
		"GTmetrix",
		"GarlikCrawler",
		"Genderanalyzer",
		"Genieo",
		"GentleSource",
		"GetLinkInfo",
		"GetRight",
		"GetURLInfo\\/[0-9]",
		"GetWeb",
		"Getintent",
		"Ghost Inspector",
		"Gigablast",
		"GigablastOpenSource",
		"Gigabot",
		"GingerCrawler",
		"Gluten Free Crawler\\/",
		"GnowitNewsbot",
		"Go [\\d\\.]* package http",
		"Go http package",
		"Go!Zilla",
		"Go-Ahead-Got-It",
		"Go-http-client",
		"GoScraper",
		"GoSpotCheck",
		"GoSquared-Status-Checker",
		"GoZilla",
		"GomezAgent",
		"Goodzer\\/[0-9]",
		"Google Keyword Suggestion",
		"Google Keyword Tool",
		"Google PP Default",
		"Google Page Speed Insights",
		"Google Search Console",
		"Google Web Preview",
		"Google favicon",
		"Google-Adwords",
		"Google-Adwords-Instant",
		"Google-Apps-Script",
		"Google-Calendar-Importer",
		"Google-HTTP-Java-Client",
		"Google-HotelAdsVerifier",
		"Google-Publisher-Plugin",
		"Google-SearchByImage",
		"Google-Site-Verification",
		"Google-Structured-Data-Testing-Tool",
		"Google-Youtube-Links",
		"GoogleCloudMonitoring",
		"GoogleDocs",
		"GoogleHC\\/",
		"GoogleProducer",
		"Googlebot-Image",
		"Googlebot-Mobile",
		"Googlebot-News",
		"Googlebot-Video",
		"Googlebot\\/",
		"Gookey",
		"Gotit",
		"Gowikibot",
		"GrabNet",
		"Grafula",
		"Grammarly",
		"GrapeFX",
		"GrapeshotCrawler",
		"Grobbot",
		"GuzzleHttp",
		"HAA(A)?RTLAND http client",
		"HEADMasterSEO",
		"HMView",
		"HTMLparser",
		"HTTP-Header-Abfrage",
		"HTTP-Tiny",
		"HTTP::Lite",
		"HTTPMon",
		"HTTP_Compression_Test",
		"HTTrack",
		"Haansoft",
		"Hatena",
		"Havij",
		"HeartRails_Capture",
		"Hloader",
		"Holmes",
		"HonesoSearchEngine\\/",
		"HootSuite Image proxy",
		"Hootsuite-WebFeed\\/[0-9]",
		"HostTracker",
		"HttpComponents",
		"HttpUrlConnection",
		"HubPages.*crawlingpolicy",
		"HubSpot ",
		"Humanlinks",
		"HyperZbozi.cz Feeder",
		"IAS crawler",
		"ICC-Crawler",
		"IDG Twitter Links Resolver",
		"IDwhois\\/[0-9]",
		"IODC",
		"IOI",
		"IPS\\/[0-9]",
		"IPWorks HTTP\\/S Component",
		"Iblog",
		"Id-search",
		"IdeelaborPlagiaat",
		"Iframely",
		"IlTrovatore",
		"ImageEngine\\/",
		"Image\\ Fetch",
		"Image\\ Sucker",
		"Imagga",
		"InAGist",
		"InDesign%20CC",
		"IndeedBot",
		"Indy\\ Library",
		"InfoTekies",
		"InfoWizards Reciprocal Link System PRO",
		"Instapaper",
		"Integrity",
		"Intelliseek",
		"InterGET",
		"InterfaxScanBot",
		"InternetSeer",
		"Internet\\ Ninja",
		"Iria",
		"Irokez",
		"IstellaBot",
		"JS-Kit",
		"James BOT",
		"Jamie's Spider",
		"Jaunt\\/",
		"Jbrofuzz",
		"Jersey\\/",
		"JetCar",
		"Jetslide",
		"Jetty",
		"Jigsaw",
		"JobFeed discovery",
		"Jobboerse",
		"Jobg8 URL Monitor",
		"Jobrapido",
		"Jobsearch1\\.5",
		"JoinVision Generic",
		"JolokiaPwn",
		"Joomla",
		"Jorgee",
		"Jugendschutzprogramm-Crawler",
		"JustView",
		"K7MLWCBot",
		"KOCMOHABT",
		"Kaspersky Lab CFR link resolver",
		"KeepRight OpenStreetMap Checker",
		"Kelny\\/",
		"Kemvibot",
		"Kerrigan\\/",
		"KeyCDN",
		"Keyword Extractor",
		"Keyword\\ Density",
		"Keywords Research",
		"KickFire",
		"KimonoLabs\\/",
		"Kml-Google",
		"KosmioBot",
		"KumKie",
		"LWP::Simple",
		"LYT\\.SR",
		"L\\.webis",
		"Landau-Media-Spider",
		"Larbin",
		"Lavf\\/",
		"LayeredExtractor",
		"LeechFTP",
		"LeechGet",
		"Leikibot",
		"Lftp",
		"LibVLC",
		"LibWeb",
		"Libwhisker",
		"Licorne Image Snapshot",
		"Liferea\\/",
		"Lightspeedsystems",
		"Likse",
		"Linguee Bot",
		"Link Valet",
		"LinkAlarm\\/",
		"LinkArchiver",
		"LinkExaminer",
		"LinkPreviewGenerator",
		"LinkScan",
		"LinkTiger",
		"LinkWalker",
		"LinkedInBot",
		"LinksManager",
		"Lipperhey",
		"Litemage_walker",
		"Livelap[bB]ot",
		"LoadImpactRload",
		"LongURL API",
		"Luminator-robots",
		"MFC_Tear_Sample",
		"MIDown\\ tool",
		"MIIxpc",
		"MJ12bot",
		"MSFrontPage",
		"MS\\ Web\\ Services\\ Client\\ Protocol",
		"MVAClient",
		"Mag-Net",
		"MagpieRSS",
		"Mail.RU_Bot",
		"Mail.Ru",
		"MailChimp",
		"Majestic12",
		"Mandrill",
		"MapperCmd",
		"MarkMonitor",
		"MarkWatch",
		"Mass\\ Downloader",
		"Mastodon",
		"Mata\\ Hari",
		"MauiBot",
		"Mediapartners \\(Googlebot\\)",
		"Mediapartners-Google",
		"Mediatoolkitbot",
		"MegaIndex",
		"MegaIndex\\.ru",
		"MeltwaterNews",
		"Melvil Rawi\\/",
		"MergeFlow-PageReader",
		"MetaJobBot",
		"MetaURI",
		"Metaspinner",
		"Microsearch",
		"Microsoft Office ",
		"Microsoft Outlook",
		"Microsoft Windows Network Diagnostics",
		"Microsoft-WebDAV-MiniRedir",
		"Microsoft\\ Data\\ Access",
		"Mindjet",
		"Miniature.io\\/",
		"Miniflux",
		"Miniflux\\/",
		"Mister\\ PiX",
		"Mnogosearch",
		"Mojeek",
		"MojeekBot\\/",
		"Mojolicious \\(Perl\\)",
		"MonTools",
		"Monit\\/",
		"Monitority\\/[0-9]",
		"Moreover",
		"Morfeus\\ Fucking\\ Scanner",
		"Morning Paper",
		"MovableType",
		"Mrcgiguy",
		"MuckRack",
		"MuckRack\\/",
		"Multiviewbot",
		"MxToolbox\\/",
		"NETCRAFT",
		"NG-Search",
		"NICErsPRO",
		"NING\\/",
		"NLNZ_IAHarvester",
		"NYU",
		"Najdi\\.si\\/",
		"Name\\ Intelligence",
		"Nameprotect",
		"Navroad",
		"NearSite",
		"Needle",
		"NerdByNature.Bot",
		"Nessus",
		"NetAnts",
		"NetLyzer",
		"NetMechanic",
		"NetShelter ContentScan",
		"NetTrack",
		"NetZIP",
		"Net\\ Vampire",
		"NetcraftSurveyAgent",
		"Netpursual",
		"Netsparker",
		"Netvibes",
		"Neustar WPM",
		"NeutrinoAPI",
		"NewRelicPinger",
		"NewsBlur .*Finder",
		"NewsGator",
		"Nexgate Ruby Client",
		"Nibbler",
		"Nikto",
		"Nimbostratus-Bot",
		"Nmap Scripting Engine",
		"Norton-Safeweb",
		"Notifixious",
		"Nuzzel",
		"Nymesis",
		"OMSC",
		"Ocarinabot",
		"Ocelli\\/[0-9]",
		"Octopus",
		"Offline Explorer",
		"Offline\\ Navigator",
		"Omea Reader",
		"Online Domain Tools",
		"OpenCalaisSemanticProxy",
		"OpenHoseBot",
		"OpenLinkProfiler",
		"OpenVAS",
		"Openfind",
		"Openstat\\/",
		"Optimizer",
		"OrangeBot\\/",
		"Orbiter",
		"OrgProbe\\/[0-9]",
		"OutclicksBot",
		"Outlook-Express",
		"Owler",
		"OxfordCloudService\\/[0-9]",
		"PEAR HTTPRequest",
		"PECL::HTTP",
		"POE-Component-Client-HTTP",
		"PR-CY.RU",
		"PRTG Network Monitor",
		"PTST ",
		"PTST\\/[0-9]+",
		"Page Analyzer",
		"Page Valet",
		"PageAnalyzer",
		"PageGrabber",
		"PagePeeker",
		"PageScorer",
		"Pagespeed\\/[0-9]",
		"Panopta",
		"Papa\\ Foto",
		"PaperLiBot",
		"Pavuk",
		"PayPal IPN",
		"Pcore-HTTP",
		"Pearltrees",
		"Peew",
		"PeoplePal",
		"Perlu -",
		"PhantomJS Screenshoter",
		"PhantomJS",
		"PhantomJS\\/",
		"Photon\\/",
		"Pi-Monster",
		"Picscout",
		"Picsearch",
		"PictureFinder",
		"Pimonster",
		"PingSpot",
		"Pingability",
		"Pingdom",
		"Pingoscope",
		"PiplBot",
		"Pixray",
		"Pizilla",
		"PleaseCrawl",
		"Ploetz \\+ Zeller",
		"Plukkie",
		"PocketParser",
		"Pockey",
		"Pompos",
		"Porkbun",
		"Port Monitor",
		"PostPost",
		"PostmanRuntime\\/",
		"PowerPoint\\/",
		"Priceonomics Analysis Engine",
		"Primalbot",
		"PrintFriendly\\.com",
		"PritTorrent\\/[0-9]",
		"PrivacyAwareBot",
		"Prlog",
		"ProWebWalker",
		"Project 25499",
		"Promotion_Tools_www.searchenginepromotionhelp.com",
		"Protopage",
		"Pulsepoint XT3 web scraper",
		"Pump",
		"Python-httplib2",
		"Python-urllib",
		"QQDownload",
		"Qirina Hurdler",
		"QrafterPro",
		"Qseero",
		"Qualidator.com SiteAnalyzer",
		"QueryN\\ Metasearch",
		"Quora Link Preview",
		"Qwantify",
		"ROI Hunter",
		"RPT-HTTPClient",
		"RSSOwl",
		"Radian6",
		"RankActive",
		"RankActiveLinkBot",
		"RankFlex",
		"RankSonicSiteAuditor",
		"ReGet",
		"Readability",
		"RealDownload",
		"RealPlayer%20Downloader",
		"RebelMouse",
		"Recorder",
		"RecurPost\\/",
		"Redirect Checker Tool",
		"ReederForMac",
		"RepoMonkey",
		"ResponseCodeTest\\/[0-9]",
		"RestSharp",
		"RetrevoPageAnalyzer",
		"Riddler",
		"Rival IQ",
		"Robosourcer",
		"Robozilla\\/[0-9]",
		"SBIder",
		"SBL-BOT",
		"SEO Browser",
		"SEOCentro",
		"SEOkicks",
		"SEOprofiler",
		"SEOstats",
		"SISTRIX",
		"SMRF URL Expander",
		"SMUrlExpander",
		"SPDYCheck",
		"SPEng",
		"SSL Labs",
		"SWIMGBot",
		"S[eE][mM]rushBot",
		"SafeDNSBot",
		"SafeSearch microdata crawler",
		"SalesIntelligent",
		"Saleslift",
		"SauceNAO",
		"ScanAlert",
		"Scoop",
		"ScoutJet",
		"ScoutURLMonitor",
		"Scrapy",
		"Scrapy",
		"Screaming Frog SEO Spider",
		"Screaming",
		"ScreenShotService\\/[0-9]",
		"Scrubby",
		"Search37\\/",
		"SearchSight",
		"Searchestate",
		"Seeker",
		"SemanticScholarBot",
		"Semiocast HTTP client",
		"Semrush",
		"Seo Servis",
		"SeoCheck",
		"Seobility",
		"Seomoz",
		"SeopultContentAnalyzer",
		"Server Density Service Monitoring",
		"SetCronJob\\/",
		"Seznam",
		"Shelob",
		"Shodan",
		"ShopWiki",
		"Shoppimon Analyzer",
		"ShoppimonAgent\\/[0-9]",
		"ShortLinkTranslate",
		"Sideqik",
		"SilverReader",
		"SimpleCrawler",
		"SimplePie",
		"SimplyFast",
		"Siphon",
		"Site-Shot\\/",
		"Site24x7",
		"SiteBar",
		"SiteCondor",
		"SiteExplorer",
		"SiteGuardian",
		"SiteIndexed",
		"SiteMonitor",
		"SiteSnagger",
		"SiteSucker",
		"SiteTruth",
		"Site\\ Sucker",
		"Sitebeam",
		"Sitebulb\\/",
		"Siteimprove",
		"Siteimprove.com",
		"Sitemap(s)? Generator",
		"Siteshooter B0t",
		"Sitevigil",
		"SkypeUriPreview",
		"SkypeUriPreview",
		"Slack-ImgProxy",
		"Slack\\/",
		"Slackbot",
		"Slurp",
		"SlySearch",
		"SmartDownload",
		"Snacktory",
		"Snake",
		"Snappy",
		"SniffRSS",
		"Snoopy",
		"SnowHaze Search",
		"SocialRankIOBot",
		"Sogou",
		"Sonic",
		"SortSite",
		"Sottopop",
		"SpaceBison",
		"SpamExperts",
		"Spammen",
		"Spanner",
		"Specificfeeds",
		"Spinn3r",
		"Sprinklr ",
		"Sqlworm",
		"Sqworm",
		"StackRambler",
		"Statastico\\/",
		"StatusCake",
		"Steeler",
		"StorygizeBot",
		"Stratagems Kumo",
		"Stroke.cz",
		"StudioFACA",
		"Sucuri",
		"Super Monitoring",
		"SuperHTTP",
		"Surphace Scout",
		"SurveyBot",
		"Suzuran",
		"SwiteScraper",
		"Symfony BrowserKit",
		"Symfony2 BrowserKit",
		"SynHttpClient-Built",
		"Sysomos",
		"Szukacz",
		"T0PHackTeam",
		"TLSProbe\\/",
		"TangibleeBot",
		"Tarantula\\/",
		"Taringa UGC",
		"TelegramBot",
		"Teleport",
		"Telesoft",
		"Telesphoreo",
		"Telesphorep",
		"Tenon\\.io",
		"Teoma",
		"Test Certificate Info",
		"Tetrahedron\\/[0-9]",
		"The Drop Reaper",
		"The Expert HTML Source Viewer",
		"The Knowledge AI",
		"TheNomad",
		"The\\ Intraformant",
		"Thinklab",
		"ThumbSniper",
		"Thumbshots",
		"TinEye",
		"Tiny Tiny RSS",
		"Toata",
		"ToutiaoSpider",
		"Traackr.com",
		"TrapitAgent",
		"Trendiction",
		"Trendsmap Resolver",
		"Trove",
		"TulipChain",
		"Turingos",
		"Turnitin",
		"TweetmemeBot",
		"Tweetminster",
		"Tweezler\\/",
		"Twice",
		"Twikle",
		"Twingly",
		"Twisted PageGetter",
		"Twitterbot",
		"Twurly",
		"Typhoeus",
		"URL Verifier",
		"URLChecker",
		"URLitor.com",
		"URLy\\ Warning",
		"URLy\\.Warning",
		"UdmSearch",
		"UniversalFeedParser",
		"Unshorten\\.It",
		"Untiny",
		"UnwindFetchor",
		"Upflow",
		"UptimeRobot",
		"Uptimia",
		"UrlTrends Ranking Updater",
		"Urlstat",
		"UsineNouvelleCrawler",
		"VB\\ Project",
		"VCI",
		"VSAgent\\/[0-9]",
		"VSB-TUO\\/[0-9]",
		"VYU2",
		"Vacuum",
		"Vagabondo",
		"Veoozbot",
		"VidibleScraper",
		"Virusdie",
		"VoidEYE",
		"Voil",
		"Vulnbusters Meter",
		"W3C-checklink",
		"W3C-mobileOK",
		"W3C_I18n-Checker",
		"W3C_Unicorn",
		"WEPA",
		"WP Engine Install Performance API",
		"WPScan",
		"WWW-Collector-E",
		"WWW-Mechanize",
		"WWW::Mechanize",
		"WWWOFFLE",
		"WallpapersHD",
		"Wallpapers\\/[0-9]+",
		"Wappalyzer",
		"WatchMouse",
		"WbSrch\\/",
		"WeCrawlForThePeace",
		"WeLikeLinks",
		"WeSEE",
		"WeSEE:Search",
		"Web-Monitoring",
		"Web-sniffer",
		"WebAuto",
		"WebCapture",
		"WebClient\\/",
		"WebCookies",
		"WebCopier",
		"WebCorp",
		"WebDoc",
		"WebEnhancer",
		"WebFetch",
		"WebFuck",
		"WebGo\\ IS",
		"WebImageCollector",
		"WebImages",
		"WebIndex",
		"WebLeacher",
		"WebPix",
		"WebReaper",
		"WebSauger",
		"WebStripper",
		"WebSucker",
		"WebThumbnail",
		"WebWhacker",
		"WebZIP",
		"Web\\ Auto",
		"Web\\ Collage",
		"Web\\ Enhancer",
		"Web\\ Fetch",
		"Web\\ Fuck",
		"Web\\ Pix",
		"Web\\ Sauger",
		"Web\\ Sucker",
		"Webalta",
		"Webauskunft",
		"Webshag",
		"Webshot",
		"Website Analyzer\\/",
		"WebsiteExtractor",
		"WebsiteQuester",
		"Website\\ Quester",
		"Websnapr\\/",
		"Webster",
		"Webthumb\\/[0-9]",
		"Wfuzz\\/",
		"WhatWeb",
		"WhatsApp",
		"WhatsMyIP",
		"WhereGoes\\?",
		"Whibse",
		"WhoRunsCoinHive",
		"Whynder Magnet",
		"WinHttpRequest",
		"Windows-RSS-Platform",
		"Woko",
		"WordPress\\/",
		"Word\\/",
		"Wtrace",
		"XING-contenttabreceiver\\/[0-9]",
		"XaxisSemanticsClassifier",
		"Xenu Link Sleuth",
		"XmlSitemapGenerator",
		"Y!J",
		"Y!J-(ASR|BSC)",
		"YaK\\/",
		"Yaanb",
		"Yahoo Ad monitoring",
		"Yahoo Link Preview",
		"YahooCacheSystem",
		"YahooYSMcm",
		"YandeG",
		"Yandex([^Search]*)",
		"YandexBot",
		"Yeti",
		"YisouSpider",
		"Yo-yo",
		"Yoleo Consumer",
		"YottaaMonitor",
		"Your-Website-Sucks\\/[0-9]",
		"Zabbix",
		"Zade",
		"Zao",
		"Zauba",
		"Zemanta Aggregator",
		"Zend\\\\\\\\Http\\\\\\\\Client",
		"Zend_Http_Client",
		"Zermelo",
		"Zeus",
		"ZnajdzFoto",
		"Zombie\\.js",
		"ZoominfoBot",
		"ZumBot",
		"ZuperlistBot\\/",
		"ZyBorg",
		"[a-z0-9\\-_]*(bot|crawler|archiver|transcoder|spider|uptime|validator|fetcher)",
		"[wW]get",
		"^COMODO DCV",
		"^Calypso v\\/",
		"^DangDang",
		"^DavClnt",
		"^FDM ",
		"^Goose\\/",
		"^Grabber",
		"^HTTPClient\\/",
		"^Java\\/",
		"^Jeode\\/",
		"^Jetty\\/",
		"^LCC ",
		"^Mail\\/",
		"^Mget",
		"^Microsoft URL Control",
		"^NG\\/[0-9\\.]",
		"^NING\\/",
		"^PHP\\/[0-9]",
		"^RMA\\/",
		"^Ruby|Ruby\\/[0-9]",
		"^VSE\\/[0-9]",
		"^WordPress\\.com",
		"^XRL\\/[0-9]",
		"^ZmEu",
		"^b0t$",
		"^bluefish ",
		"^git\\/",
		"^scrutiny\\/",
		"a3logics\\.in",
		"a\\.pr-cy\\.ru",
		"aboutthedomain",
		"acapbot",
		"acoon",
		"acoonbot",
		"acrylicapps\\.com\\/pulp",
		"adbeat",
		"adbeat_bot",
		"adressendeutschland",
		"adscanner",
		"adscanner\\/",
		"agentslug",
		"aiHitBot",
		"aihit",
		"aiohttp\\/",
		"akka-http\\/",
		"akula\\/",
		"alertra",
		"alexa site audit",
		"allloadin\\.com",
		"alyze\\.info",
		"amagit",
		"antibot",
		"arabot",
		"arachnode",
		"archive.org_bot",
		"aria2",
		"asafaweb.com",
		"asynchttp",
		"autocite",
		"axios",
		"axios\\/",
		"backlink-check",
		"backlinkcrawler",
		"baidu\\.com",
		"baypup\\/[0-9]",
		"baypup\\/colbert",
		"betaBot",
		"biNu image cacher",
		"bibnum.bnf",
		"biglotron",
		"bingbot",
		"binlar",
		"bitlybot",
		"biz_Directory",
		"blekkobot",
		"blogmuraBot",
		"bnf.fr_bot",
		"boitho\\.com-dc",
		"bot-pge.chlooe.com",
		"botify",
		"brainobot",
		"buzzbot",
		"cXensebot",
		"careerbot",
		"catexplorador",
		"cb crawl",
		"centurybot9",
		"cg-eye",
		"changedetection",
		"check_http",
		"checkprivacy",
		"chkme\\.com",
		"citeseerxbot",
		"clips\\.ua\\.ac\\.be",
		"cmcm\\.com",
		"coccoc",
		"cognitiveseo",
		"collection@infegy.com",
		"colly -",
		"contactbigdatafr",
		"content crawler spider",
		"contentkingapp",
		"contxbot",
		"convera",
		"copyright sheriff",
		"crawler4j",
		"cron-job\\.org",
		"curb",
		"curl",
		"cuwhois\\/[0-9]",
		"cybo\\.com",
		"datagnionbot",
		"dataprovider",
		"dcrawl",
		"deadlinkchecker",
		"developers\\.google\\.com\\/\\+\\/web\\/snippet\\/",
		"discobot",
		"dlvr",
		"docoloc",
		"domaincrawler",
		"dotMailer content retrieval",
		"dotSemantic",
		"dotbot",
		"downforeveryoneorjustme",
		"downnotifier\\.com",
		"drupact",
		"dubaiindex",
		"eCairn-Grabber",
		"eCatch",
		"eContext\\/",
		"ec2linkfinder",
		"echocrawl",
		"edisterbot",
		"electricmonk",
		"elefent",
		"elisabot",
		"epicbot",
		"eright",
		"europarchive.org",
		"europarchive\\.org",
		"evc-batch",
		"exabot",
		"ezooms",
		"facebookexternalhit",
		"facebookplatform",
		"fairshare",
		"fasthttp",
		"feeltiptop",
		"filterdb.iss.net\\/crawler",
		"findlink",
		"findthatfile",
		"findxbot",
		"fluffy",
		"flynxapp",
		"forensiq",
		"fr-crawler",
		"free thumbnails",
		"fuelbot",
		"g00g1e.net",
		"g00g1e\\.net",
		"g2reader-bot",
		"gSOAP\\/",
		"ganarvisitas\\/[0-9]",
		"geek-tools",
		"getprismatic\\.com",
		"github-camo",
		"github\\.com\\/",
		"gnam gnam spider",
		"gobyus",
		"gofetch",
		"gooblog",
		"google-xrawler",
		"google_partner_monitoring",
		"gosquared-thumbnailer",
		"grabify",
		"grokkit",
		"grouphigh",
		"grub-client",
		"grub.org",
		"gslfbot",
		"gvfs\\/",
		"hackney\\/",
		"hawkReader",
		"help@dataminr\\.com",
		"heritrix",
		"historious\\/",
		"hledejLevne\\.cz\\/[0-9]",
		"hosterstats",
		"ht:\\/\\/check",
		"htdig",
		"http-get",
		"http-kit",
		"http-request\\/",
		"http\\.rb\\/",
		"http_get",
		"http_request2",
		"http_requester",
		"httphr",
		"httpscheck",
		"httpssites_power",
		"httpunit",
		"httrack",
		"huaweisymantec",
		"i2kconnect\\/",
		"iZSearch",
		"ia_archiver",
		"ichiro",
		"igdeSpyder",
		"imgsizer",
		"imrbot",
		"inbound\\.li parser",
		"infegy",
		"infohelfer",
		"inpwrd\\.com",
		"instabid",
		"integromedb",
		"intelium_bot",
		"internetVista monitor",
		"internet_archive",
		"intraVnews",
		"ip-web-crawler.com",
		"iplabel",
		"ips-agent",
		"iqdb\\/",
		"isitup\\.org",
		"iskanie",
		"it2media-domain-crawler",
		"janforman",
		"jobo",
		"jyxobot",
		"knows\\.is",
		"kouio",
		"kube-probe",
		"kulturarw3",
		"lb-spider",
		"letsencrypt",
		"libwww",
		"link checker",
		"linkCheck",
		"link_thumbnailer",
		"linkapediabot",
		"linkdex",
		"linkfluence",
		"linkpeek",
		"lipperhey",
		"livedoor ScreenShot",
		"looksystems\\.net",
		"lssbot",
		"lssrocketcrawler",
		"ltx71",
		"lua-resty-http",
		"lwp-request",
		"lwp-trivial",
		"lycos",
		"mShots",
		"mabontland",
		"magpie-crawler",
		"makecontact\\/",
		"mappydata",
		"marketinggrader",
		"masscan\\/[0-9]",
		"mediawords",
		"memorybot",
		"mindUpBot",
		"mixdata dot com",
		"mixed-content-scan",
		"mixnode",
		"mlbot",
		"moatbot",
		"mogimogi",
		"monitis",
		"montastic",
		"mowser",
		"msnbot",
		"msrbot",
		"muhstik-scan",
		"nWormFeedFinder",
		"nagios",
		"nerdybot",
		"netEstate NE Crawler",
		"netresearch",
		"netresearchserver",
		"newsharecounts",
		"newsme",
		"newspaper\\/",
		"niki-bot",
		"nineconnections\\.com",
		"node-superagent",
		"node-urllib\\/",
		"node\\.io",
		"nominet\\.org\\.uk",
		"notifyninja",
		"nuhk",
		"nutch",
		"oegp",
		"okhttp",
		"omgili",
		"openindexspider",
		"orion-semantics",
		"ow\\.ly",
		"ownCloud News",
		"page2rss",
		"page\\ scorer",
		"page_verifier",
		"panscient",
		"parsijoo",
		"pcBrowser",
		"peerindex",
		"phpcrawl",
		"phpservermon",
		"ping\\.blo\\.gs\\/",
		"pingdom",
		"pinterest",
		"pinterest\\.com",
		"plumanalytics",
		"postano",
		"postrank",
		"probethenet",
		"prospectb2b",
		"proximic",
		"psbot",
		"pshtt, https scanning",
		"purebot",
		"python-requests",
		"redback\\/",
		"redditbot",
		"request\\.js",
		"rogerbot",
		"safe-agent-scanner",
		"scalaj-http",
		"scan\\.lol",
		"scooter",
		"scribdbot",
		"search\\.thunderstone",
		"seekbot",
		"semanticbot",
		"semanticdiscovery",
		"semanticjuice",
		"sentry\\/",
		"seo-nastroj.cz",
		"seoscanners",
		"servernfo\\.com",
		"sexsearcher",
		"seznambot",
		"shrinktheweb",
		"sistrix crawler",
		"sitebot",
		"siteexplorer.info",
		"sitexy\\.com",
		"slider\\.com",
		"slurp",
		"smtbot",
		"sniptracker",
		"sogou web",
		"sovereign\\.ai",
		"spaziodati",
		"spbot",
		"speedy",
		"spray-can",
		"spyonweb",
		"sqlmap",
		"ssl-tools",
		"suchen",
		"summify",
		"sysscan",
		"tAkeOut",
		"tagoobot",
		"teoma",
		"terrainformatica\\.com",
		"theinternetrules",
		"theoldreader\\.com",
		"toplistbot",
		"topster",
		"touche.com",
		"tracemyfile",
		"trendictionbot",
		"trendspottr\\.com",
		"truwoGPS",
		"turnitinbot",
		"tweetedtimes\\.com",
		"twengabot",
		"twibble",
		"uCrawlr\\/",
		"ubermetrics-technologies",
		"uclassify",
		"um-LN",
		"updated",
		"updown\\.io daemon",
		"urlappendbot",
		"urlresolver",
		"vBSEO",
		"vebidoobot",
		"via ggpht\\.com GoogleImageProxy",
		"visionutils",
		"vkShare",
		"voilabot",
		"voltron",
		"voyager\\/",
		"w3af\\.org",
		"wangling",
		"wbsearchbot",
		"web-archive-net.com.bot",
		"web-capture\\.net",
		"webcollage",
		"webcompanycrawler",
		"webkit2png",
		"webmastercoffee",
		"webmon ",
		"webscreenie",
		"websitepulse agent",
		"websitepulse[+ ]checker",
		"wf84",
		"wget",
		"wkhtmlto",
		"wmtips",
		"wocbot",
		"woobot",
		"woriobot",
		"wotbox",
		"wpif",
		"wprecon\\.com survey",
		"wscheck",
		"www\\.monitor\\.us",
		"x09Mozilla",
		"x22Mozilla",
		"xovibot",
		"xpymep([0-9]?)\\.exe",
		"yacy",
		"yacybot",
		"yandex.com\\/bots",
		"yanga",
		"yeti",
		"yoogliFetchAgent",
		"yoozBot",
		"yourls\\.org",
		"zgrab",
		".*Java.*outbrain",
	}
}
